version: '3.8'

services:
  vue-app:
    container_name: vue-dev
    build: .
    ports:
      - "5173:5173"  # Mapea el puerto de Vite
    volumes:
      - .:/app  # Monta tu código fuente dentro del contenedor
      - /app/node_modules  # Evita sobrescribir `node_modules`
    environment:
      - CHOKIDAR_USEPOLLING=true  # Para que detecte cambios en WSL
    command: ["npm", "run", "dev", "--", "--host"]
